// zy73117/src/components/NotificationToast.tsx
import { X, AlertTriangle, CheckCircle, Info, AlertCircle, ArrowRight } from 'lucide-react';
import { useStore } from '@/store/useStore';
import type { NotificationItem } from '@/types';

const toastIcons = {
  error: AlertCircle,
  warning: AlertTriangle,
  info: Info,
  success: CheckCircle,
};

const toastColors = {
  error: 'border-danger-600 bg-danger-900/90 text-danger-200',
  warning: 'border-warning-600 bg-warning-900/90 text-warning-200',
  info: 'border-primary-600 bg-primary-900/90 text-primary-200',
  success: 'border-success-600 bg-success-900/90 text-success-200',
};

const iconColors = {
  error: 'text-danger-400',
  warning: 'text-warning-400',
  info: 'text-primary-400',
  success: 'text-success-400',
};

interface ToastProps {
  notification: NotificationItem;
}

function Toast({ notification }: ToastProps) {
  const removeNotification = useStore((state) => state.removeNotification);
  const Icon = toastIcons[notification.type];

  return (
    <div
      className={`w-full max-w-sm border rounded-lg shadow-xl backdrop-blur-sm p-4 animate-slide-in-right ${toastColors[notification.type]}`}
    >
      <div className="flex items-start gap-3">
        <Icon className={`w-5 h-5 flex-shrink-0 mt-0.5 ${iconColors[notification.type]}`} />
        <div className="flex-1 min-w-0">
          <h4 className="font-medium text-sm mb-1">{notification.title}</h4>
          <p className="text-xs opacity-90 mb-2">{notification.message}</p>
          {notification.nextStep && (
            <div className="bg-black/20 rounded p-2 mb-2">
              <p className="text-xs flex items-start gap-1.5">
                <ArrowRight className="w-3 h-3 mt-0.5 flex-shrink-0" />
                <span>{notification.nextStep}</span>
              </p>
            </div>
          )}
          {notification.actions && notification.actions.length > 0 && (
            <div className="flex gap-2">
              {notification.actions.map((action, idx) => (
                <button
                  key={idx}
                  onClick={() => {
                    action.onClick();
                    removeNotification(notification.id);
                  }}
                  className="text-xs bg-white/10 hover:bg-white/20 px-3 py-1 rounded transition-colors"
                >
                  {action.label}
                </button>
              ))}
            </div>
          )}
        </div>
        <button
          onClick={() => removeNotification(notification.id)}
          className="p-1 hover:bg-white/10 rounded transition-colors flex-shrink-0"
        >
          <X className="w-4 h-4 opacity-70" />
        </button>
      </div>
    </div>
  );
}

export function NotificationToast() {
  const notifications = useStore((state) => state.notifications);

  if (notifications.length === 0) return null;

  return (
    <div className="fixed top-4 right-4 z-50 space-y-3">
      {notifications.map((notification) => (
        <Toast key={notification.id} notification={notification} />
      ))}
    </div>
  );
}

// zy72271/src/components/common/NotificationToast.vue
<script setup lang="ts">
import { CheckCircle, XCircle, AlertTriangle, Info, X } from 'lucide-vue-next';
import { useNotificationStore } from '@/stores/notification';
import type { Notification } from '@/types';

const store = useNotificationStore();

const iconMap: Record<Notification['type'], any> = {
  success: CheckCircle,
  error: XCircle,
  warning: AlertTriangle,
  info: Info,
};

const colorMap: Record<Notification['type'], string> = {
  success: 'bg-green-50 border-green-200 text-green-800',
  error: 'bg-red-50 border-red-200 text-red-800',
  warning: 'bg-amber-50 border-amber-200 text-amber-800',
  info: 'bg-blue-50 border-blue-200 text-blue-800',
};

const iconColorMap: Record<Notification['type'], string> = {
  success: 'text-green-500',
  error: 'text-red-500',
  warning: 'text-amber-500',
  info: 'text-blue-500',
};
</script>

<template>
  <div class="fixed top-4 right-4 z-50 space-y-3 w-96">
    <TransitionGroup name="notification">
      <div
        v-for="notification in store.state.notifications"
        :key="notification.id"
        class="flex items-start p-4 border rounded-lg shadow-lg backdrop-blur-sm"
        :class="colorMap[notification.type]"
      >
        <component
          :is="iconMap[notification.type]"
          class="w-5 h-5 mt-0.5 flex-shrink-0"
          :class="iconColorMap[notification.type]"
        />
        <p class="ml-3 text-sm flex-1">{{ notification.message }}</p>
        <button
          class="ml-2 text-slate-400 hover:text-slate-600 transition-colors"
          @click="store.removeNotification(notification.id)"
        >
          <X class="w-4 h-4" />
        </button>
      </div>
    </TransitionGroup>
  </div>
</template>

<style scoped>
.notification-enter-active,
.notification-leave-active {
  transition: all 0.3s ease;
}
.notification-enter-from {
  opacity: 0;
  transform: translateX(100%);
}
.notification-leave-to {
  opacity: 0;
  transform: translateX(100%);
}
</style>
