// zy72271/src/components/layout/StepProgress.vue
<script setup lang="ts">
import { CheckCircle2, Circle } from 'lucide-vue-next';
import { STEP_NAMES } from '@/types';

interface Props {
  currentStep: number;
  completedSteps?: number[];
}

const props = withDefaults(defineProps<Props>(), {
  completedSteps: () => [],
});

const isCompleted = (index: number) => props.completedSteps.includes(index) || index < props.currentStep;
const isCurrent = (index: number) => index === props.currentStep;
</script>

<template>
  <div class="w-full py-6">
    <div class="flex items-center justify-between">
      <template v-for="(step, index) in STEP_NAMES" :key="index">
        <div class="flex flex-col items-center flex-1">
          <div
            class="relative flex items-center justify-center w-10 h-10 rounded-full border-2 transition-all duration-300"
            :class="{
              'bg-green-500 border-green-500 text-white': isCompleted(index),
              'bg-white border-[#1e3a5f] text-[#1e3a5f]': isCurrent(index),
              'bg-white border-slate-300 text-slate-400': !isCompleted(index) && !isCurrent(index),
            }"
          >
            <CheckCircle2 v-if="isCompleted(index)" class="w-5 h-5" />
            <Circle v-else class="w-5 h-5" />
          </div>
          <span
            class="mt-2 text-sm font-medium transition-colors duration-300"
            :class="{
              'text-green-600': isCompleted(index),
              'text-[#1e3a5f]': isCurrent(index),
              'text-slate-400': !isCompleted(index) && !isCurrent(index),
            }"
          >
            {{ step }}
          </span>
        </div>
        <div
          v-if="index < STEP_NAMES.length - 1"
          class="flex-1 h-0.5 mx-2 transition-colors duration-300"
          :class="isCompleted(index) ? 'bg-green-500' : 'bg-slate-200'"
        ></div>
      </template>
    </div>
  </div>
</template>

// zy72596/src/components/StepProgress.tsx
import { Check } from 'lucide-react';
import { ReviewStep, STEP_LABELS } from '@/types';

interface StepProgressProps {
  currentStep: ReviewStep;
  onAdvance?: () => void;
  canAdvance?: boolean;
}

const steps: ReviewStep[] = ['log_import', 'threshold_note', 'summary_update'];

export function StepProgress({ currentStep, onAdvance, canAdvance = true }: StepProgressProps) {
  const currentIdx = steps.indexOf(currentStep);

  return (
    <div className="flex items-center justify-between w-full max-w-3xl mx-auto">
      {steps.map((step, idx) => {
        const isCompleted = idx < currentIdx;
        const isCurrent = idx === currentIdx;
        return (
          <div key={step} className="flex items-center flex-1">
            <div className="flex flex-col items-center relative z-10">
              <div
                className={`w-10 h-10 rounded-full flex items-center justify-center border-2 transition-all duration-300 ${
                  isCompleted
                    ? 'bg-green-600 border-green-600 text-white'
                    : isCurrent
                    ? 'bg-primary-800 border-primary-800 text-white'
                    : 'bg-white border-primary-200 text-primary-400'
                }`}
              >
                {isCompleted ? (
                  <Check size={18} />
                ) : (
                  <span className="text-sm font-semibold">{idx + 1}</span>
                )}
              </div>
              <span
                className={`mt-2 text-xs font-medium ${
                  isCurrent ? 'text-primary-800' : isCompleted ? 'text-green-600' : 'text-primary-400'
                }`}
              >
                {STEP_LABELS[step]}
              </span>
            </div>
            {idx < steps.length - 1 && (
              <div
                className={`flex-1 h-0.5 mx-2 -mt-6 transition-all duration-300 ${
                  idx < currentIdx ? 'bg-green-500' : 'bg-primary-200'
                }`}
              />
            )}
          </div>
        );
      })}
    </div>
  );
}
