// zy72007/src/components/record/RecordList.tsx
import { useNavigate } from 'react-router-dom';
import { Eye } from 'lucide-react';
import { useRecordStore } from '../../store/recordStore';
import StatusBadge from '../layout/StatusBadge';
import { formatCurrency } from '../../utils/exportUtil';

export default function RecordList() {
  const navigate = useNavigate();
  const { getFilteredRecords } = useRecordStore();
  const records = getFilteredRecords();

  return (
    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-200">
              <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                投资者
              </th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                投资金额
              </th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                状态
              </th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                材料数
              </th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                处理人
              </th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                最后更新
              </th>
              <th className="px-6 py-3 text-right text-xs font-semibold text-gray-600 uppercase tracking-wider">
                操作
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {records.map((record, index) => (
              <tr
                key={record.id}
                className={`hover:bg-primary-50 transition-colors cursor-pointer ${
                  index % 2 === 0 ? 'bg-white' : 'bg-gray-50/50'
                }`}
                onClick={() => navigate(`/record/${record.id}`)}
              >
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="font-medium text-gray-900">{record.investorName}</div>
                  <div className="text-xs text-gray-500">ID: {record.id}</div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className="font-semibold text-gray-900">
                    {formatCurrency(record.amount)}
                  </span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <StatusBadge status={record.status} size="sm" />
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className="text-sm text-gray-600">{record.materials.length} 份</span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className="text-sm text-gray-600">{record.handler}</span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className="text-sm text-gray-500">{record.updatedAt}</span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-right">
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      navigate(`/record/${record.id}`);
                    }}
                    className="inline-flex items-center space-x-1 px-3 py-1.5 text-sm text-primary-700 hover:bg-primary-100 rounded-lg transition-colors"
                  >
                    <Eye className="w-4 h-4" />
                    <span>查看详情</span>
                  </button>
                </td>
              </tr>
            ))}
            {records.length === 0 && (
              <tr>
                <td colSpan={7} className="px-6 py-12 text-center text-gray-500">
                  暂无符合条件的记录
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// zy71813/src/components/RecordList.vue
<template>
  <div class="card overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full">
        <thead class="bg-gray-50 border-b border-gray-200">
          <tr>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">记录编号</th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">门店</th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">账期</th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">来源</th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">金额</th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">问题分类</th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">状态</th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">版本</th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">更新时间</th>
            <th class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">告警</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <tr
            v-for="record in records"
            :key="record.id"
            @click="$emit('select', record.id)"
            :class="[
              'cursor-pointer transition-colors hover:bg-gray-50',
              selectedId === record.id ? 'bg-primary-50' : ''
            ]"
          >
            <td class="px-4 py-3">
              <span class="font-mono text-sm text-gray-900">{{ record.id }}</span>
            </td>
            <td class="px-4 py-3">
              <div class="text-sm">
                <div class="font-medium text-gray-900">{{ record.storeName }}</div>
                <div class="text-gray-500">{{ record.storeId }}</div>
              </div>
            </td>
            <td class="px-4 py-3 text-sm text-gray-600">{{ record.accountingPeriod }}</td>
            <td class="px-4 py-3">
              <span class="inline-flex items-center gap-1 text-sm text-gray-600">
                <span>{{ SOURCE_ICONS[record.source] }}</span>
                {{ SOURCE_LABELS[record.source] }}
              </span>
            </td>
            <td class="px-4 py-3">
              <span class="text-sm font-semibold text-gray-900">¥{{ record.amount.toFixed(2) }}</span>
            </td>
            <td class="px-4 py-3">
              <span class="text-sm text-gray-600">{{ CATEGORY_LABELS[record.issueCategory] }}</span>
            </td>
            <td class="px-4 py-3">
              <span :class="[
                'inline-flex px-2 py-1 text-xs font-medium rounded-full border',
                STATUS_COLORS[record.status]
              ]">
                {{ STATUS_LABELS[record.status] }}
              </span>
            </td>
            <td class="px-4 py-3">
              <span class="text-sm text-gray-500">v{{ record.currentVersion }}</span>
            </td>
            <td class="px-4 py-3">
              <span class="text-sm text-gray-500">{{ formatDate(record.updatedAt) }}</span>
            </td>
            <td class="px-4 py-3">
              <div v-if="record.latestAlert || record.hasUnresolvedChanges">
                <span
                  v-if="record.hasUnresolvedChanges"
                  class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-full bg-red-100 text-red-700"
                >
                  ⚠️ 结论变更
                </span>
                <span
                  v-if="record.latestAlert"
                  class="block mt-1 text-xs text-orange-600"
                  title="record.latestAlert"
                >
                  版本异常
                </span>
              </div>
              <span v-else class="text-sm text-gray-400">-</span>
            </td>
          </tr>
          <tr v-if="records.length === 0">
            <td colspan="10" class="px-4 py-12 text-center text-gray-500">
              暂无匹配的记录
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { format } from 'date-fns';
import type { ShortageRecord } from '../types';
import { STATUS_LABELS, STATUS_COLORS, SOURCE_LABELS, SOURCE_ICONS, CATEGORY_LABELS } from '../constants/labels';

defineProps<{
  records: ShortageRecord[];
  selectedId: string | null;
}>();

defineEmits<{
  (e: 'select', id: string): void;
}>();

function formatDate(dateStr: string): string {
  return format(new Date(dateStr), 'MM-dd HH:mm');
}
</script>
