// xy10659/client/src/views/Reports.vue
<template>
  <div class="reports">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>报表导出</span>
        </div>
      </template>

      <el-tabs v-model="activeTab">
        <el-tab-pane label="核销记录报表" name="verifications">
          <el-form :inline="true" :model="verificationForm" class="search-form">
            <el-form-item label="开始日期">
              <el-date-picker v-model="verificationForm.start_date" type="date" value-format="YYYY-MM-DD" />
            </el-form-item>
            <el-form-item label="结束日期">
              <el-date-picker v-model="verificationForm.end_date" type="date" value-format="YYYY-MM-DD" />
            </el-form-item>
            <el-form-item label="经办人">
              <el-input v-model="verificationForm.handler" placeholder="经办人" clearable />
            </el-form-item>
            <el-form-item label="仅显示异常">
              <el-checkbox v-model="verificationForm.has_exception" />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" @click="exportVerifications">
                <el-icon><Download /></el-icon>
                导出Excel
              </el-button>
            </el-form-item>
          </el-form>
        </el-tab-pane>

        <el-tab-pane label="异常记录报表" name="exceptions">
          <el-form :inline="true" :model="exceptionForm" class="search-form">
            <el-form-item label="开始日期">
              <el-date-picker v-model="exceptionForm.start_date" type="date" value-format="YYYY-MM-DD" />
            </el-form-item>
            <el-form-item label="结束日期">
              <el-date-picker v-model="exceptionForm.end_date" type="date" value-format="YYYY-MM-DD" />
            </el-form-item>
            <el-form-item label="状态">
              <el-select v-model="exceptionForm.status" placeholder="状态" clearable>
                <el-option label="待处理" value="pending" />
                <el-option label="已解决" value="resolved" />
              </el-select>
            </el-form-item>
            <el-form-item label="修正人">
              <el-input v-model="exceptionForm.corrected_by" placeholder="修正人" clearable />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" @click="exportExceptions">
                <el-icon><Download /></el-icon>
                导出Excel
              </el-button>
            </el-form-item>
          </el-form>
        </el-tab-pane>

        <el-tab-pane label="车辆里程报表" name="vehicles">
          <el-form :inline="true" :model="vehicleForm" class="search-form">
            <el-form-item label="负责人">
              <el-input v-model="vehicleForm.responsible_person" placeholder="负责人" clearable />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" @click="exportVehicles">
                <el-icon><Download /></el-icon>
                导出Excel
              </el-button>
            </el-form-item>
          </el-form>
        </el-tab-pane>
      </el-tabs>
    </el-card>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue';
import axios from 'axios';
import { ElMessage } from 'element-plus';

const activeTab = ref('verifications');

const verificationForm = reactive({
  start_date: '',
  end_date: '',
  handler: '',
  has_exception: false
});

const exceptionForm = reactive({
  start_date: '',
  end_date: '',
  status: '',
  corrected_by: ''
});

const vehicleForm = reactive({
  responsible_person: ''
});

const exportVerifications = async () => {
  try {
    const params = {
      start_date: verificationForm.start_date,
      end_date: verificationForm.end_date,
      handler: verificationForm.handler,
      has_exception: verificationForm.has_exception
    };
    
    const res = await axios.get('/api/reports/verifications', {
      params,
      responseType: 'blob'
    });
    
    const url = window.URL.createObjectURL(new Blob([res.data]));
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `verification_report_${new Date().getTime()}.xlsx`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    
    ElMessage.success('导出成功');
  } catch (err) {
    ElMessage.error('导出失败');
  }
};

const exportExceptions = async () => {
  try {
    const params = {
      start_date: exceptionForm.start_date,
      end_date: exceptionForm.end_date,
      status: exceptionForm.status,
      corrected_by: exceptionForm.corrected_by
    };
    
    const res = await axios.get('/api/reports/exceptions', {
      params,
      responseType: 'blob'
    });
    
    const url = window.URL.createObjectURL(new Blob([res.data]));
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `exception_report_${new Date().getTime()}.xlsx`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    
    ElMessage.success('导出成功');
  } catch (err) {
    ElMessage.error('导出失败');
  }
};

const exportVehicles = async () => {
  try {
    const params = {
      responsible_person: vehicleForm.responsible_person
    };
    
    const res = await axios.get('/api/reports/vehicles', {
      params,
      responseType: 'blob'
    });
    
    const url = window.URL.createObjectURL(new Blob([res.data]));
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `vehicle_report_${new Date().getTime()}.xlsx`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    
    ElMessage.success('导出成功');
  } catch (err) {
    ElMessage.error('导出失败');
  }
};
</script>

<style scoped>
.reports {
  padding: 0;
}
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.search-form {
  margin: 20px 0;
}
</style>

// xy10696/client/src/pages/Reports.jsx
import React, { useState } from 'react'
import { Card, Form, Select, Button, message, Space, DatePicker } from 'antd'
import { DownloadOutlined } from '@ant-design/icons'
import axios from 'axios'
import dayjs from 'dayjs'

const { Option } = Select
const { RangePicker } = DatePicker

function Reports() {
  const [form] = Form.useForm()
  const [loading, setLoading] = useState(false)

  const handleExport = async () => {
    try {
      const values = await form.validateFields()
      setLoading(true)

      const params = {
        responsible_person: values.responsible_person,
        start_date: values.date_range ? values.date_range[0].format('YYYY-MM-DD') : undefined,
        end_date: values.date_range ? values.date_range[1].format('YYYY-MM-DD') : undefined,
      }

      const res = await axios.get('/api/reports/export', {
        params,
        responseType: 'blob',
      })

      const url = window.URL.createObjectURL(new Blob([res.data]))
      const link = document.createElement('a')
      link.href = url
      link.setAttribute('download', `导出报表_${dayjs().format('YYYYMMDDHHmmss')}.xlsx`)
      document.body.appendChild(link)
      link.click()
      link.remove()
      window.URL.revokeObjectURL(url)

      message.success('导出成功')
    } catch (error) {
      message.error('导出失败')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div>
      <div style={{ marginBottom: 16 }}>
        <h2>报告导出</h2>
      </div>

      <Card title="导出报表">
        <Form form={form} layout="vertical">
          <Form.Item
            name="date_range"
            label="时间范围"
          >
            <RangePicker 
              style={{ width: '100%' }} 
              placeholder={['开始日期', '结束日期']}
            />
          </Form.Item>

          <Form.Item
            name="responsible_person"
            label="责任人/操作人"
          >
            <Select 
              placeholder="输入责任人姓名过滤" 
              showSearch
              allowClear
            >
              <Option value="管理员">管理员</Option>
            </Select>
          </Form.Item>

          <Form.Item>
            <Space>
              <Button 
                type="primary" 
                icon={<DownloadOutlined />} 
                onClick={handleExport}
                loading={loading}
              >
                导出Excel报表
              </Button>
              <Button onClick={() => form.resetFields()}>
                重置
              </Button>
            </Space>
          </Form.Item>
        </Form>

        <Card type="inner" title="报表包含内容" style={{ marginTop: 16 }}>
          <ul>
            <li><strong>审计日志</strong>：所有字段变更记录，包含表名、字段名、原值、新值、操作人、时间</li>
            <li><strong>流转记录</strong>：所有设备流转记录，包含设备编号、流转类型、前后数据、操作人、时间</li>
            <li><strong>异常记录</strong>：所有异常记录，包含设备编号、异常类型、描述、状态、责任人、操作人、时间</li>
          </ul>
        </Card>
      </Card>
    </div>
  )
}

export default Reports
