// zy71813/src/components/FilterBar.vue
<template>
  <div class="card p-4 mb-6">
    <div class="flex flex-wrap gap-4 items-center">
      <div class="flex items-center gap-2">
        <span class="text-sm font-medium text-gray-600">状态：</span>
        <div class="flex gap-1">
          <button
            v-for="(label, key) in STATUS_LABELS"
            :key="key"
            @click="toggleStatus(key)"
            :class="[
              'px-3 py-1 text-sm rounded-full border transition-colors',
              isStatusSelected(key)
                ? STATUS_COLORS[key]
                : 'bg-gray-50 text-gray-500 border-gray-200 hover:bg-gray-100'
            ]"
          >
            {{ label }}
          </button>
        </div>
      </div>
      
      <div class="flex items-center gap-2">
        <label class="text-sm font-medium text-gray-600">账期：</label>
        <select v-model="selectedPeriod" @change="applyPeriod" class="input text-sm py-1">
          <option value="">全部</option>
          <option value="2024-05">2024年5月</option>
          <option value="2024-04">2024年4月</option>
          <option value="2024-03">2024年3月</option>
        </select>
      </div>
      
      <div class="flex items-center gap-2">
        <label class="text-sm font-medium text-gray-600">门店：</label>
        <input
          v-model="searchStore"
          @input="applyStoreFilter"
          type="text"
          placeholder="输入门店编号"
          class="input text-sm py-1 w-32"
        />
      </div>
      
      <label class="flex items-center gap-2 cursor-pointer">
        <input
          type="checkbox"
          :checked="onlyUnresolved"
          @change="applyUnresolvedFilter"
          class="w-4 h-4 text-primary-600 rounded"
        />
        <span class="text-sm font-medium text-gray-600">仅看有告警</span>
      </label>

      <button
        @click="resetFilters"
        class="btn-secondary text-sm py-1 ml-auto"
      >
        重置筛选
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useShortageStore } from '../composables/useShortageStore';
import { STATUS_LABELS, STATUS_COLORS } from '../constants/labels';
import type { RecordStatus } from '../types';

const { setFilters, filters } = useShortageStore();

const selectedPeriod = ref(filters.value.period || '');
const searchStore = ref(filters.value.storeId || '');
const onlyUnresolved = ref(filters.value.hasUnresolvedChanges || false);

function isStatusSelected(status: string): boolean {
  return filters.value.status?.includes(status as RecordStatus) ?? false;
}

function toggleStatus(status: string) {
  const current = filters.value.status || [];
  const newStatus = current.includes(status as RecordStatus)
    ? current.filter(s => s !== status)
    : [...current, status as RecordStatus];
  setFilters({ status: newStatus.length > 0 ? newStatus : undefined });
}

function applyPeriod() {
  setFilters({ period: selectedPeriod.value || undefined });
}

function applyStoreFilter() {
  setFilters({ storeId: searchStore.value || undefined });
}

function applyUnresolvedFilter(e: Event) {
  const target = e.target as HTMLInputElement;
  setFilters({ hasUnresolvedChanges: target.checked || undefined });
}

function resetFilters() {
  selectedPeriod.value = '';
  searchStore.value = '';
  onlyUnresolved.value = false;
  setFilters({
    status: undefined,
    period: undefined,
    storeId: undefined,
    hasUnresolvedChanges: undefined
  });
}
</script>

// zy10271/src/components/FilterBar.tsx
import React from 'react'
import { OrderStatus } from '../types'
import { useOrderContext } from '../store/OrderContext'
import { STATUS_LABELS } from '../utils/statusUtils'
import { Search, Filter } from 'lucide-react'

const FILTER_OPTIONS: (OrderStatus | 'rework')[] = [
  'pending',
  'measuring',
  'cutting',
  'polishing',
  'edging',
  'quality-check',
  'rework',
  'ready',
  'picked-up'
]

export const FilterBar: React.FC = () => {
  const { filters, setFilters } = useOrderContext()

  const handleStatusToggle = (status: OrderStatus | 'rework') => {
    const currentStatus = filters.status || []
    let newStatus: OrderStatus[]
    
    if (status === 'rework') {
      setFilters({ hasRework: !filters.hasRework })
      return
    }
    
    if (currentStatus.includes(status)) {
      newStatus = currentStatus.filter(s => s !== status)
    } else {
      newStatus = [...currentStatus, status]
    }
    
    setFilters({ status: newStatus.length > 0 ? newStatus : undefined })
  }

  const isActive = (status: OrderStatus | 'rework') => {
    if (status === 'rework') return filters.hasRework
    return filters.status?.includes(status as OrderStatus)
  }

  return (
    <div className="bg-white rounded-lg shadow p-4 mb-6">
      <div className="flex items-center gap-2 mb-3">
        <Filter size={18} className="text-gray-500" />
        <span className="font-medium text-gray-700">筛选</span>
      </div>
      
      <div className="flex flex-wrap gap-2 mb-4">
        {FILTER_OPTIONS.map((status) => (
          <button
            key={status}
            onClick={() => handleStatusToggle(status)}
            className={`px-3 py-1.5 rounded-full text-sm transition ${
              isActive(status)
                ? 'bg-blue-500 text-white'
                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            }`}
          >
            {status === 'rework' ? '返工中' : STATUS_LABELS[status]}
          </button>
        ))}
        
        <button
          onClick={() => setFilters({ status: undefined, hasRework: undefined })}
          className="px-3 py-1.5 rounded-full text-sm bg-gray-200 text-gray-600 hover:bg-gray-300 transition"
        >
          清除筛选
        </button>
      </div>

      <div className="relative">
        <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
        <input
          type="text"
          placeholder="搜索订单号、客户名、电话..."
          value={filters.search || ''}
          onChange={(e) => setFilters({ search: e.target.value || undefined })}
          className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        />
      </div>
    </div>
  )
}
