// zy72271/src/components/common/StatusBadge.vue
<script setup lang="ts">
import type { RecordStatus } from '@/types';

interface Props {
  status: RecordStatus;
  size?: 'sm' | 'md';
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
});

const statusConfig: Record<RecordStatus, { label: string; class: string }> = {
  'pending': {
    label: '待处理',
    class: 'bg-slate-100 text-slate-700 border-slate-200',
  },
  'cad-imported': {
    label: 'CAD已导入',
    class: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  'under-review': {
    label: '审核中',
    class: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  'pending-manager': {
    label: '待经理复核',
    class: 'bg-orange-50 text-orange-700 border-orange-200 animate-pulse',
  },
  'corrected': {
    label: '已修正',
    class: 'bg-purple-50 text-purple-700 border-purple-200',
  },
  'report-generated': {
    label: '报告已生成',
    class: 'bg-green-50 text-green-700 border-green-200',
  },
};

const sizeClasses = {
  sm: 'px-2 py-0.5 text-xs',
  md: 'px-3 py-1 text-sm',
};

const config = statusConfig[props.status] || statusConfig['pending'];
</script>

<template>
  <span
    class="inline-flex items-center font-medium border rounded"
    :class="[config.class, sizeClasses[size]]"
  >
    <span
      class="w-1.5 h-1.5 rounded-full mr-1.5"
      :class="{
        'bg-slate-400': status === 'pending',
        'bg-blue-500': status === 'cad-imported',
        'bg-amber-500': status === 'under-review',
        'bg-orange-500': status === 'pending-manager',
        'bg-purple-500': status === 'corrected',
        'bg-green-500': status === 'report-generated',
      }"
    ></span>
    {{ config.label }}
  </span>
</template>

// zy72311/src/components/StatusBadge.tsx
import type { RecordStatus } from '@/store/useStore'

const statusConfig: Record<RecordStatus, { label: string; className: string }> = {
  normal: { label: '正常', className: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30' },
  zero_denominator_empty: { label: '分母为0', className: 'bg-rose-500/15 text-rose-400 border-rose-500/30' },
  supplemented: { label: '补录', className: 'bg-amber-500/15 text-amber-400 border-amber-500/30' },
  pending: { label: '待处理', className: 'bg-slate-500/15 text-slate-400 border-slate-500/30' },
  review: { label: '待复核', className: 'bg-amber-500/15 text-amber-400 border-amber-500/30' },
  confirmed: { label: '已确认', className: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30' },
  rejected: { label: '已驳回', className: 'bg-rose-500/15 text-rose-400 border-rose-500/30' },
}

export default function StatusBadge({ status }: { status: RecordStatus }) {
  const config = statusConfig[status] || statusConfig.pending
  return (
    <span
      className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium border ${config.className}`}
    >
      {config.label}
    </span>
  )
}
