// zy71398/src/components/Layout.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  LayoutDashboard,
  FileUp,
  AlertTriangle,
  RotateCcw,
  History,
  FileBarChart,
  Database
} from 'lucide-vue-next'

const route = useRoute()
const router = useRouter()

const navItems = [
  { path: '/', label: '仪表盘概览', icon: LayoutDashboard },
  { path: '/import', label: '导入预演工作台', icon: FileUp },
  { path: '/conflicts', label: '冲突队列中心', icon: AlertTriangle },
  { path: '/rollback', label: '回滚计划引擎', icon: RotateCcw },
  { path: '/history', label: '历史审计追踪', icon: History },
  { path: '/reports', label: '演练报告中心', icon: FileBarChart }
]

const activePath = computed(() => route.path)
</script>

<template>
  <div class="flex h-screen bg-slate-50">
    <aside class="w-64 bg-white border-r border-slate-200 flex flex-col">
      <div class="h-16 flex items-center px-6 border-b border-slate-200">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 bg-primary-600 rounded-xl flex items-center justify-center">
            <Database class="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 class="font-bold text-slate-900">数据导入</h1>
            <p class="text-xs text-slate-500">回滚演练系统</p>
          </div>
        </div>
      </div>
      
      <nav class="flex-1 p-4 space-y-1 overflow-y-auto scrollbar-thin">
        <button
          v-for="item in navItems"
          :key="item.path"
          @click="router.push(item.path)"
          :class="activePath === item.path ? 'nav-item-active' : 'nav-item'"
        >
          <component :is="item.icon" class="w-5 h-5" />
          <span>{{ item.label }}</span>
        </button>
      </nav>
      
      <div class="p-4 border-t border-slate-200">
        <div class="flex items-center gap-3 px-4 py-3">
          <div class="w-8 h-8 bg-slate-200 rounded-full flex items-center justify-center">
            <span class="text-sm font-medium text-slate-600">运</span>
          </div>
          <div class="flex-1 min-w-0">
            <p class="text-sm font-medium text-slate-900 truncate">运营专员</p>
            <p class="text-xs text-slate-500 truncate">operator@company.com</p>
          </div>
        </div>
      </div>
    </aside>
    
    <main class="flex-1 flex flex-col overflow-hidden">
      <header class="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-6">
        <div>
          <h2 class="text-lg font-semibold text-slate-900">
            {{ navItems.find(n => n.path === activePath)?.label || '数据导入回滚演练系统' }}
          </h2>
        </div>
        <div class="flex items-center gap-3">
          <span class="text-sm text-slate-500">{{ new Date().toLocaleDateString('zh-CN') }}</span>
        </div>
      </header>
      
      <div class="flex-1 overflow-y-auto p-6 scrollbar-thin">
        <slot />
      </div>
    </main>
  </div>
</template>

// zy71863/src/components/Layout.tsx
import { ReactNode } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { FileText, GitBranch, BookOpen, Home } from 'lucide-react';

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const location = useLocation();

  const navItems = [
    { path: '/', label: '复核记录', icon: FileText },
    { path: '/guide', label: '操作指南', icon: BookOpen },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-primary-50">
      <header className="bg-white/80 backdrop-blur-sm border-b border-primary-100 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-gradient-to-br from-primary-600 to-primary-800 rounded-xl flex items-center justify-center shadow-lg">
                <GitBranch className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-lg font-bold text-primary-800 font-serif">概率树复核系统</h1>
                <p className="text-xs text-primary-500">Probability Tree Review</p>
              </div>
            </div>
            <nav className="flex items-center space-x-1">
              {navItems.map((item) => {
                const Icon = item.icon;
                const isActive = location.pathname === item.path;
                return (
                  <Link
                    key={item.path}
                    to={item.path}
                    className={`flex items-center space-x-2 px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${
                      isActive
                        ? 'bg-primary-100 text-primary-800 shadow-sm'
                        : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    <span>{item.label}</span>
                  </Link>
                );
              })}
            </nav>
          </div>
        </div>
      </header>
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {children}
      </main>
      <footer className="border-t border-primary-100 bg-white/50 mt-auto">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <p className="text-center text-sm text-slate-500">
            概率树复核系统 · 让教研流程更清晰
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Layout;
