// zy72271/src/components/common/StatusBadge.vue
<script setup lang="ts">
import type { RecordStatus } from '@/types';

interface Props {
  status: RecordStatus;
  size?: 'sm' | 'md';
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
});

const statusConfig: Record<RecordStatus, { label: string; class: string }> = {
  'pending': {
    label: '待处理',
    class: 'bg-slate-100 text-slate-700 border-slate-200',
  },
  'cad-imported': {
    label: 'CAD已导入',
    class: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  'under-review': {
    label: '审核中',
    class: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  'pending-manager': {
    label: '待经理复核',
    class: 'bg-orange-50 text-orange-700 border-orange-200 animate-pulse',
  },
  'corrected': {
    label: '已修正',
    class: 'bg-purple-50 text-purple-700 border-purple-200',
  },
  'report-generated': {
    label: '报告已生成',
    class: 'bg-green-50 text-green-700 border-green-200',
  },
};

const sizeClasses = {
  sm: 'px-2 py-0.5 text-xs',
  md: 'px-3 py-1 text-sm',
};

const config = statusConfig[props.status] || statusConfig['pending'];
</script>

<template>
  <span
    class="inline-flex items-center font-medium border rounded"
    :class="[config.class, sizeClasses[size]]"
  >
    <span
      class="w-1.5 h-1.5 rounded-full mr-1.5"
      :class="{
        'bg-slate-400': status === 'pending',
        'bg-blue-500': status === 'cad-imported',
        'bg-amber-500': status === 'under-review',
        'bg-orange-500': status === 'pending-manager',
        'bg-purple-500': status === 'corrected',
        'bg-green-500': status === 'report-generated',
      }"
    ></span>
    {{ config.label }}
  </span>
</template>

// zy72007/src/components/layout/StatusBadge.tsx
import { RecordStatus, RecordStatusLabel } from '../../types';

interface StatusBadgeProps {
  status: RecordStatus;
  size?: 'sm' | 'md';
}

const statusStyles: Record<RecordStatus, string> = {
  [RecordStatus.PENDING]: 'bg-gray-100 text-gray-700 border-gray-300',
  [RecordStatus.CONFIRMED]: 'bg-green-50 text-status-confirmed border-green-200',
  [RecordStatus.PENDING_MATERIAL]: 'bg-amber-50 text-status-pending border-amber-200',
  [RecordStatus.MANUAL_ADJUSTED]: 'bg-red-50 text-status-adjusted border-red-200',
};

const statusDotStyles: Record<RecordStatus, string> = {
  [RecordStatus.PENDING]: 'bg-gray-400',
  [RecordStatus.CONFIRMED]: 'bg-status-confirmed',
  [RecordStatus.PENDING_MATERIAL]: 'bg-status-pending',
  [RecordStatus.MANUAL_ADJUSTED]: 'bg-status-adjusted',
};

export default function StatusBadge({ status, size = 'md' }: StatusBadgeProps) {
  const sizeClasses = size === 'sm' ? 'px-2 py-0.5 text-xs' : 'px-3 py-1 text-sm';

  return (
    <span
      className={`inline-flex items-center space-x-1.5 rounded-full border ${sizeClasses} ${statusStyles[status]}`}
    >
      <span className={`w-2 h-2 rounded-full ${statusDotStyles[status]}`}></span>
      <span className="font-medium">{RecordStatusLabel[status]}</span>
    </span>
  );
}
